apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-user-config
  labels:
    app: clickhousep-user-config
data:
  users.xml: |-
    <yandex>
      <profiles>
        <default>
          <max_memory_usage>10000000000</max_memory_usage>
          <use_uncompressed_cache>0</use_uncompressed_cache>
          <load_balancing>random</load_balancing>
        </default>
      </profiles>
      <users replace="replace">
        <default>
          <password>{{ .Values.clickhouse.password }}</password>
          <profile>{{ .Values.clickhouse.user }}</profile>
          <quota>default</quota>
          <networks>
            <ip>::/0</ip>
          </networks>
        </default>
      </users>
    </yandex>
